export const doctors = [
  {
    id: '1',
    name: 'Ariella Mccarty',
    imageUrl:
      'https://plus.unsplash.com/premium_photo-1661580574627-9211124e5c3f?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8ZG9jdG9yfGVufDB8fDB8fHww',
    location: '1601 Center St, Mobile, USA',
    price: '$100',
    rating: 4.5,
    speciality: 'Cardiologist',
    experience: '10 years',
    description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    date: '23 April, 2019',
    time: '2:25 PM',
  },
  {
    id: '2',
    name: 'Camron Barr',
    imageUrl:
      'https://img.freepik.com/premium-photo/close-up-portrait-his-he-nice-attractive-smart-clever-cheerful-cheery-doc-professor-emergency-center-owner-director-ceo-boss-chief-isolated-light-white-gray-pastel-color_274222-21030.jpg',
    location: '2451 USA Medical Center, USA',
    price: '$250',
    rating: 4.0,
    speciality: 'Dermatologist',
    experience: '8 years',
    description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    date: '23 April, 2019',
    time: '2:25 PM',
  },
  {
    id: '3',
    name: 'Clare Barajas',
    imageUrl:
      'https://i.pinimg.com/474x/7b/de/b5/7bdeb59ac67e572286c16718a96c6138.jpg',
    location: '320 WestLake Ave, 98109, USA',
    price: '$150',
    rating: 4.2,
    speciality: 'Neurologist',
    experience: '12 years',
    description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    date: '23 April, 2019',
    time: '2:25 PM',
  },
  {
    id: '4',
    name: 'Daphne Ellison',
    imageUrl: 'https://randomuser.me/api/portraits/women/44.jpg',
    location: '982 Greenway Rd, Austin, USA',
    price: '$200',
    rating: 4.7,
    speciality: 'Pediatrician',
    experience: '9 years',
    description: 'Providing the best pediatric care for children of all ages.',
    date: '12 May, 2020',
    time: '3:00 PM',
  },
  {
    id: '5',
    name: 'Elijah Cross',
    imageUrl: 'https://randomuser.me/api/portraits/men/46.jpg',
    location: '45 Jefferson St, Brooklyn, USA',
    price: '$180',
    rating: 4.6,
    speciality: 'Orthopedic Surgeon',
    experience: '15 years',
    description: 'Expert in treating musculoskeletal conditions and injuries.',
    date: '8 June, 2021',
    time: '1:45 PM',
  },
  {
    id: '6',
    name: 'Fiona Novak',
    imageUrl: 'https://randomuser.me/api/portraits/women/52.jpg',
    location: '22 Lakeview Blvd, Chicago, USA',
    price: '$220',
    rating: 4.8,
    speciality: 'Gynecologist',
    experience: '11 years',
    description:
      'Committed to providing excellent women’s healthcare services.',
    date: '17 August, 2021',
    time: '10:30 AM',
  },
  {
    id: '7',
    name: 'George Patel',
    imageUrl: 'https://randomuser.me/api/portraits/men/40.jpg',
    location: '877 Park Ave, San Francisco, USA',
    price: '$300',
    rating: 4.9,
    speciality: 'Oncologist',
    experience: '20 years',
    description: 'Specialist in cancer treatment and research.',
    date: '9 September, 2022',
    time: '4:15 PM',
  },
  {
    id: '8',
    name: 'Harriet Benson',
    imageUrl: 'https://randomuser.me/api/portraits/women/29.jpg',
    location: '673 Maple Dr, Denver, USA',
    price: '$130',
    rating: 4.3,
    speciality: 'Psychiatrist',
    experience: '7 years',
    description:
      'Helping patients with mental health and emotional well-being.',
    date: '11 October, 2022',
    time: '11:20 AM',
  },
  {
    id: '9',
    name: 'Isaac Rivera',
    imageUrl: 'https://randomuser.me/api/portraits/men/38.jpg',
    location: '12 Bluebird Ln, Miami, USA',
    price: '$170',
    rating: 4.5,
    speciality: 'Endocrinologist',
    experience: '13 years',
    description: 'Specialist in treating hormone-related disorders.',
    date: '15 November, 2022',
    time: '9:30 AM',
  },
  {
    id: '10',
    name: 'Jasmine Thornton',
    imageUrl: 'https://randomuser.me/api/portraits/women/37.jpg',
    location: '67 Oak St, Seattle, USA',
    price: '$140',
    rating: 4.4,
    speciality: 'Rheumatologist',
    experience: '10 years',
    description: 'Expert in autoimmune diseases and arthritis treatments.',
    date: '5 December, 2023',
    time: '2:10 PM',
  },
  {
    id: '11',
    name: 'Kyle Simmons',
    imageUrl: 'https://randomuser.me/api/portraits/men/42.jpg',
    location: '234 Willow St, Los Angeles, USA',
    price: '$280',
    rating: 4.8,
    speciality: 'Nephrologist',
    experience: '18 years',
    description: 'Dedicated to treating kidney diseases and disorders.',
    date: '14 January, 2024',
    time: '5:20 PM',
  },
  {
    id: '12',
    name: 'Lena Vasquez',
    imageUrl: 'https://randomuser.me/api/portraits/women/45.jpg',
    location: '555 Sunset Blvd, Las Vegas, USA',
    price: '$190',
    rating: 4.6,
    speciality: 'Pulmonologist',
    experience: '14 years',
    description: 'Specialist in respiratory diseases and lung health.',
    date: '20 February, 2024',
    time: '1:30 PM',
  },
];

export const patients = [
  {
    id: '1',
    name: 'Khalil Solis',
    imageUrl:
      'https://www.shutterstock.com/image-photo/businessman-glasses-showing-smile-260nw-1685161834.jpg',
    date: '23 April, 2019',
    time: '2:25 PM',
    Location: '1601 Center St, NY 56565, USA',
    description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    rating: 4.5,
    ratingDate: '30 March, 2024',
    ratingTime: '5:30 PM',
    ratingRelative: 'Yesterday',
  },
  {
    id: '2',
    name: 'Emily Carter',
    imageUrl:
      'https://www.shutterstock.com/image-photo/smiling-female-doctor-posing-office-260nw-1022452042.jpg',
    date: '12 May, 2020',
    time: '10:15 AM',
    Location: '45 East St, CA 78541, USA',
    description:
      'Emily is visiting for a routine check-up and health assessment.',
    rating: 4.8,
    ratingDate: '29 March, 2024',
    ratingTime: '8:45 AM',
    ratingRelative: '2 days ago',
  },
  {
    id: '3',
    name: 'David Johnson',
    imageUrl:
      'https://www.shutterstock.com/image-photo/portrait-smiling-young-man-casual-260nw-1757969975.jpg',
    date: '5 March, 2021',
    time: '1:00 PM',
    Location: '789 Maple Ave, TX 45098, USA',
    description:
      'David is scheduled for a follow-up appointment regarding his previous treatment.',
    rating: 4.2,
    ratingDate: '28 March, 2024',
    ratingTime: '7:15 PM',
    ratingRelative: '3 days ago',
  },
  {
    id: '4',
    name: 'Sophia Martinez',
    imageUrl:
      'https://www.shutterstock.com/image-photo/portrait-young-woman-smiling-260nw-1834321477.jpg',
    date: '18 July, 2022',
    time: '3:45 PM',
    Location: '256 Oak St, FL 33609, USA',
    description:
      'Sophia has an appointment for a dental check-up and cleaning.',
    rating: 4.9,
    ratingDate: '31 March, 2024',
    ratingTime: '9:00 AM',
    ratingRelative: 'Today',
  },
  {
    id: '5',
    name: 'Liam Anderson',
    imageUrl:
      'https://www.shutterstock.com/image-photo/happy-young-man-casual-shirt-260nw-1739099982.jpg',
    date: '29 August, 2023',
    time: '11:30 AM',
    Location: '999 Pine St, WA 98101, USA',
    description:
      'Liam is consulting a specialist regarding his recent health concerns.',
    rating: 4.3,
    ratingDate: '27 March, 2024',
    ratingTime: '6:50 PM',
    ratingRelative: '4 days ago',
  },
  {
    id: '6',
    name: 'Olivia Brown',
    imageUrl:
      'https://www.shutterstock.com/image-photo/portrait-young-woman-long-hair-260nw-1234567890.jpg',
    date: '15 September, 2023',
    time: '9:15 AM',
    Location: '123 Birch St, NY 10001, USA',
    description:
      'Olivia has a wellness consultation and general health check-up scheduled.',
    rating: 4.7,
    ratingDate: '30 March, 2024',
    ratingTime: '11:20 AM',
    ratingRelative: 'Yesterday',
  },
  {
    id: '7',
    name: 'Ethan Wilson',
    imageUrl:
      'https://www.shutterstock.com/image-photo/portrait-young-man-glasses-260nw-1987654321.jpg',
    date: '30 October, 2023',
    time: '4:20 PM',
    Location: '654 Elm St, AZ 85210, USA',
    description: 'Ethan is undergoing physical therapy for a sports injury.',
    rating: 4.6,
    ratingDate: '29 March, 2024',
    ratingTime: '2:00 PM',
    ratingRelative: '2 days ago',
  },
  {
    id: '8',
    name: 'Ava Miller',
    imageUrl:
      'https://www.shutterstock.com/image-photo/smiling-woman-casual-attire-260nw-1122334455.jpg',
    date: '10 November, 2023',
    time: '2:10 PM',
    Location: '321 Cedar St, IL 60616, USA',
    description:
      'Ava is attending a consultation for dietary and fitness guidance.',
    rating: 4.4,
    ratingDate: '31 March, 2024',
    ratingTime: '10:30 AM',
    ratingRelative: 'Today',
  },
];

export const timeSlots = [
  '09:00 AM',
  '10:00 AM',
  '11:00 AM',
  '01:00 PM',
  '02:00 PM',
  '03:00 PM',
  '04:00 PM',
  '05:00 PM',
];
